const ItemNames = {
  AxeStone: 'meleeToolRepairT0StoneAxe',
  AxeTazasStone: 'meleeToolRepairT0TazasStoneAxe',
  AxeFireaxe: 'meleeToolAxeT1IronFireaxe',
  AxeSteel: 'meleeToolAxeT2SteelAxe',

  PickaxeIron: 'meleeToolPickT1IronPickaxe',
  PickaxeSteel: 'meleeToolPickT2SteelPickaxe',

  HammerClaw: 'meleeToolRepairT1ClawHammer',
  HammerStone: 'meleeWpnSledgeT0StoneSledgehammer',
  HammerIron: 'meleeWpnSledgeT1IronSledgehammer',
  HammerSteel: 'meleeWpnSledgeT3SteelSledgehammer',

  ShovelStone: 'meleeToolShovelT0StoneShovel',
  ShovelIron: 'meleeToolShovelT1IronShovel',
  ShovelSteel: 'meleeToolShovelT2SteelShovel',

  Chainsaw: 'meleeToolAxeT3Chainsaw',
  Auger: 'meleeToolPickT3Auger',
  Wrench: 'meleeToolSalvageT1Wrench',
  Ratchet: 'meleeToolSalvageT2Ratchet',
  ImpactDriver: 'meleeToolSalvageT3ImpactDriver',

  KnifeBone: 'meleeWpnBladeT0BoneKnife',
  KnifeHunting: 'meleeWpnBladeT1HuntingKnife',
  KnifeCandy: 'meleeWpnBladeT1CandyKnife',
  KnifeBladeMachete: 'meleeWpnBladeT3Machete',

  ClubWooden: 'meleeWpnClubT0WoodenClub',
  ClubBaseball: 'meleeWpnClubT1BaseballBat',
  ClubCandy: 'meleeWpnClubT1CandyClub',
  ClubSteel: 'meleeWpnClubT3SteelClub',

  BatonJunk: 'meleeWpnBatonT1JunkBaton',
  BatonStun: 'meleeWpnBatonT2StunBaton',
  BatonPlasma: 'meleeWpnBatonT3PlasmaBaton',

  SpearStone: 'meleeWpnSpearT0StoneSpear',
  SpearIron: 'meleeWpnSpearT1IronSpear',
  SpearSteel: 'meleeWpnSpearT3SteelSpear',

  KnucklesLeather: 'meleeWpnKnucklesT0LeatherKnuckles',
  KnucklesIron: 'meleeWpnKnucklesT1IronKnuckles',
  KnucklesSteel: 'meleeWpnKnucklesT3SteelKnuckles',

  HoeIron: 'meleeToolFarmT1IronHoe',
  SledgeJunk: 'gunBotT1JunkSledge',
  TurretJunk: 'gunBotT2JunkTurret',

  HandMaster: 'meleeHandMaster',
  HandPlayer: 'meleeHandPlayer',
  HandZombie01: 'meleeHandZombie01',
  HandZombieFeral: 'meleeHandZombieFeral',
  HandZombieFeral02: 'meleeHandZombie02Feral',
  HandZombieBurning: 'meleeHandZombieBurning',
  HandZombieBurningFeral: 'meleeHandZombieBurningFeral',
  HandZombieBurningCrawler: 'meleeHandZombieBurningCrawler',
  HandZombieCop: 'meleeHandZombieCop',
  HandZombieCopFeral: 'meleeHandZombieCopFeral',
  HandZombieCopRadiated: 'meleeHandZombieCopRadiated',
  HandZombieStrong: 'meleeHandZombieStrong',
  HandZombieStrongFeral: 'meleeHandZombieStrongFeral',
  HandZombieDemolition: 'meleeHandZombieDemolition',
  HandZombieWorker: 'meleeHandZombieWorker',
  HandZombieWorkerFeral: 'meleeHandZombieWorkerFeral',
  HandZombieFootballPlayerFeral: 'meleeHandZombieFootballPlayerFeral',
  HandZombieStripper: 'meleeHandZombieStripper',
  HandZombieStripperFeral: 'meleeHandZombieStripperFeral',
  HandZombieHazMatFeral: 'meleeHandZombieHazMatFeral',

  HandAnimalBossGracee: 'meleeHandBossGrace',
  HandAnimalCoyote: 'meleeHandAnimalCoyote',
  HandAnimalZombieDog: 'meleeHandAnimalZombieDog',
  HandAnimalZombieBear: 'meleeHandAnimalZombieBear',
  HandAnimalBear: 'meleeHandAnimalBear',
  HandAnimalBearFeral: 'meleeHandAnimalZombieBearFeral',
  HandAnimalZombieVulture: 'meleeHandAnimalZombieVulture',
  HandAnimalZombieVultureRadiated: 'meleeHandAnimalZombieVultureRadiated',
  HandAnimalSnake: 'meleeHandAnimalSnake',
  HandAnimalWolf: 'meleeHandAnimalWolf',
  HandAnimalWolfDire: 'meleeHandAnimalDireWolf',

  ProjectileZombieVomit: 'ammoProjectileZombieVomit',
  ProjectileZombieVomitFeral: 'ammoProjectileZombieVomitFeral',
  ProjectileZombieVomitRadiated: 'ammoProjectileZombieVomitRadiated',

  BowPrimitive: 'gunBowT0PrimitiveBow',
  BowWooden: 'gunBowT1WoodenBow',
  BowCompound: 'gunBowT3CompoundBow',
  BowCrossbow: 'gunBowT1IronCrossbow',
  BowCrossbowCompound: 'gunBowT3CompoundCrossbow',

  gunHandgunT1Pistol: 'gunHandgunT1Pistol',
  gunHandgunT3SMG5: 'gunHandgunT3SMG5',
  gunHandgunT2Magnum44: 'gunHandgunT2Magnum44',
  gunHandgunT3DesertVulture: 'gunHandgunT3DesertVulture',
  gunShotgunT0Blunderbuss: 'gunShotgunT0Blunderbuss',
  gunShotgunT1DoubleBarrel: 'gunShotgunT1DoubleBarrel',
  gunShotgunT2PumpShotgun: 'gunShotgunT2PumpShotgun',
  gunShotgunT3AutoShotgun: 'gunShotgunT3AutoShotgun',
  gunRifleT1HuntingRifle: 'gunRifleT1HuntingRifle',
  gunRifleT2MarksmanRifle: 'gunRifleT2MarksmanRifle',
  gunRifleT3SniperRifle: 'gunRifleT3SniperRifle',
  gunMGT1AK47: 'gunMGT1AK47',
  gunMGT2TacticalAR: 'gunMGT2TacticalAR',
  gunMGT3M60: 'gunMGT3M60',

  ammoArrowStone: 'ammoArrowStone',
  ammoArrowIron: 'ammoArrowIron',
  ammoArrowSteelAP: 'ammoArrowSteelAP',
  ammoArrowFlaming: 'ammoArrowFlaming',
  ammoArrowExploding: 'ammoArrowExploding',
  ammoCrossbowBoltStone: 'ammoCrossbowBoltStone',
  ammoCrossbowBoltIron: 'ammoCrossbowBoltIron',
  ammoCrossbowBoltSteelAP: 'ammoCrossbowBoltSteelAP',
  ammoCrossbowBoltFlaming: 'ammoCrossbowBoltFlaming',
  ammoCrossbowBoltExploding: 'ammoCrossbowBoltExploding',
  ammo9mm: 'ammo9mmBulletBall',
  ammo9mmHP: 'ammo9mmBulletHP',
  ammo9mmAP: 'ammo9mmBulletAP',
  ammo44mm: 'ammo44MagnumBulletBall',
  ammo44mmHP: 'ammo44MagnumBulletHP',
  ammo44mmAP: 'ammo44MagnumBulletAP',
  ammo762mm: 'ammo762mmBulletBall',
  ammo762mmHP: 'ammo762mmBulletHP',
  ammo762mmAP: 'ammo762mmBulletAP',
  ammoShotgunShell: 'ammoShotgunShell',
  ammoShotgunSlug: 'ammoShotgunSlug',
  ammoShotgunBreachingSlug: 'ammoShotgunBreachingSlug',
  ammoBlunderbuss: 'ammoBlunderbuss',
  ammoJunkTurretRegular: 'ammoJunkTurretRegular',
  ammoJunkTurretShell: 'ammoJunkTurretShell',
  ammoJunkTurretAP: 'ammoJunkTurretAP',
  ammoRocketHE: 'ammoRocketHE', // Explosion.EntityDamage
  ammoRocketFrag: 'ammoRocketFrag', // Explosion.EntityDamage
  ammoFlare: 'thrownAmmoFlare',
  ammoDartIron: 'ammoDartIron',
  ammoDartIron: 'ammoDartIron',

  explosiveGrenade: 'thrownGrenade',
  explosiveGrenadeContact: 'thrownGrenadeContact',
  explosiveC4: 'thrownTimedCharge',
  explosiveDynamite: 'thrownDynamite',
  explosiveMolotov: 'thrownAmmoMolotovCocktail',
};

module.exports = { ItemNames };
